### 内嵌函数（内部函数）

Python的函数是允许内嵌定义的，即在函数内创建另一个函数

```py
def test1():

    print('test1()正在被调用')

    def test2():

        print('test2()正在被调用')

    test2()

```

这个例子似乎没什么用，而且看起来还比较蠢，但是终归是一个例子

关于内嵌函数使用需要注意的一个地方，在内部函数整个作用域，都在外部函数之内，比如我们这个例子，我们的test2\(\)函数整个作用域都在外部函数test1\(\)内，除了在test1\(\)这个函数内可以随意调用test2\(\)之外，没有其他方式可以调用test2\(\)这个函数

### 闭包

在函数式编程中一个重要的语法结构，典型的函数式编程就是lisp,以前学CAD的时候了解过，Python中的闭包从表现形式上，如果在一个内部函数里，对外部作用域\(但不是在全局作用域\)的变量引用那么内部函数就会被认为是闭包，讲了一堆，确实很难理解，我们还是在举个栗子

```py
def test1(x):    
    def test2(y):        
        return x * y    
    return test2

```

test2\(\)就是一个内嵌函数，她的外部作用域就是test1\(\)的函数体内，对外部作用域的变量引用\(x就是test1的变量\)，那么达到这两点的话，这个就是闭包了，接下来我们看一下怎么调用？

a  = test1\(5\)\(8\)

这样就可以调用了

`test1(5)(8)`

接下来我们来看一看我们经常对于这种内部函数我们会经常犯错的地方

```py

def test1():

    x = 5

    def test2():

        x = x+x

        return x

    return test2()

```

这个时候我们调用test1\(\)就会报错，

> Traceback \(most recent call last\):
> 
> File "demo3.py", line 48, in &lt;module&gt;
> 
> test1\(\)
> 
> File "demo3.py", line 46, in test1
> 
> return test2\(\)
> 
> File "demo3.py", line 44, in test2
> 
> x = x+x
> 
> UnboundLocalError: local variable 'x' referenced before assignment

我们可以看到这个报错信息，提示我们局部变量x 不能够在未定义前使用，因为执行test1\(\)的时候，return了一个test2\(\)函数，这个时候会去执行test2\(\)，但是这个时候test2这个函数，x是没有定义的，这个时候x是一个非全局变量的外部变量，如果我们试图对这个x试图修改的时候，外部变量的x会被暂时的屏蔽起来，（就像我们的局部变量和全局变量一样，在函数里面修改全部变量，会新建一个局部变量），在Python3之前这个问题是无解的，只能通过一些容器来解决。

但是我们在python3中可以使用nonlocal关键字，这个关键字使用跟global使用一样

```
def test1():
    x = 5 def test2(): nonlocal x#声明x不是一个局部变量 x = x+x return x return test2()

print(test1())
```



